import { SportConfig, SportKey } from "@/types";

export const SPORTS: Record<SportKey, SportConfig> = {
  basketball: {
    key: "basketball",
    label: "Basketball",
    icon: require("../assets/icons/sport-basketball.png"),
    periodName: "Quarter",
    periodNamePlural: "Quarters",
    totalPeriods: 4,
  },
  football: {
    key: "football",
    label: "Football",
    icon: require("../assets/icons/sport-football.png"),
    periodName: "Quarter",
    periodNamePlural: "Quarters",
    totalPeriods: 4,
  },
  soccer: {
    key: "soccer",
    label: "Soccer",
    icon: require("../assets/icons/sport-soccer.png"),
    periodName: "Half",
    periodNamePlural: "Halves",
    totalPeriods: 2,
  },
  hockey: {
    key: "hockey",
    label: "Hockey",
    icon: require("../assets/icons/sport-hockey.png"),
    periodName: "Period",
    periodNamePlural: "Periods",
    totalPeriods: 3,
  },
  baseball: {
    key: "baseball",
    label: "Baseball",
    icon: require("../assets/icons/sport-baseball.png"),
    periodName: "Inning",
    periodNamePlural: "Innings",
    totalPeriods: 9,
  },
  tennis: {
    key: "tennis",
    label: "Tennis",
    icon: require("../assets/icons/sport-tennis.png"),
    periodName: "Set",
    periodNamePlural: "Sets",
    totalPeriods: 3,
  },
  swimming: {
    key: "swimming",
    label: "Swimming",
    icon: require("../assets/icons/sport-swimming.png"),
    periodName: "Lap",
    periodNamePlural: "Laps",
    totalPeriods: 4,
  },
  track_field: {
    key: "track_field",
    label: "Track & Field",
    icon: require("../assets/icons/sport-track-field.png"),
    periodName: "Leg",
    periodNamePlural: "Legs",
    totalPeriods: 4,
  },
  volleyball: {
    key: "volleyball",
    label: "Volleyball",
    icon: require("../assets/icons/sport-volleyball.png"),
    periodName: "Set",
    periodNamePlural: "Sets",
    totalPeriods: 3,
  },
  softball: {
    key: "softball",
    label: "Softball",
    icon: require("../assets/icons/sport-softball.png"),
    periodName: "Inning",
    periodNamePlural: "Innings",
    totalPeriods: 7,
  },
  wrestling: {
    key: "wrestling",
    label: "Wrestling",
    icon: require("../assets/icons/sport-wrestling.png"),
    periodName: "Period",
    periodNamePlural: "Periods",
    totalPeriods: 3,
  },
  lacrosse: {
    key: "lacrosse",
    label: "Lacrosse",
    icon: require("../assets/icons/sport-lacrosse.png"),
    periodName: "Quarter",
    periodNamePlural: "Quarters",
    totalPeriods: 4,
  },
  golf: {
    key: "golf",
    label: "Golf",
    icon: require("../assets/icons/sport-golf.png"),
    periodName: "Round",
    periodNamePlural: "Rounds",
    totalPeriods: 4,
  },
  gymnastics: {
    key: "gymnastics",
    label: "Gymnastics",
    icon: require("../assets/icons/sport-gymnastics.png"),
    periodName: "Rotation",
    periodNamePlural: "Rotations",
    totalPeriods: 4,
  },
  other: {
    key: "other",
    label: "Other Sport",
    icon: require("../assets/icons/sport-other-medal.png"),
    periodName: "Phase",
    periodNamePlural: "Phases",
    totalPeriods: 4,
  },
};

export const SPORT_LIST: SportConfig[] = Object.values(SPORTS);
